apiVersion: v1
kind: Pod
metadata: 
  name: lemmy-go-users
  labels: 
    app: lemmy-go-users
spec:
  containers:
  - name: lemmy-go-users
    image: registry.gitlab.com/lemmygo/lemmygousers
    env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          name: mongourl
          key: mongourl
  imagePullSecrets:
  - name: regcred