apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmy-go-user
  labels:
    app: lemmy-go-users
spec:
  replicas: 1
  template:
    metadata:
      name: lemmy-go-users
      labels:
        app: lemmy-go-users
    spec:
      containers:
      - name: lemmy-go-users
        image: registry.gitlab.com/lemmygo/lemmygousers:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: mongourl
              key: mongourl
      imagePullSecrets:
      - name: regcred
  selector:
    matchLabels:
      app: lemmy-go-users

