apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmy-go-user
  namespace: lemmygo
  labels:
    app: lemmy-go-users
spec:
  replicas: 1
  template:
    metadata:
      name: lemmy-go-users
      labels:
        app: lemmy-go-users
    spec:
      containers:
      - name: lemmy-go-users
        image: registry.gitlab.com/lemmygo/lemmygousers:latest
        ports:
        - containerPort: 8081
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: mongourl
              key: mongourl
      - name: lemmy-envoy
        image: registry.gitlab.com/lemmygo/lemmy-envoy
      imagePullSecrets:
      - name: regcred
  selector:
    matchLabels:
      app: lemmy-go-users
---
apiVersion: v1
kind: Service
metadata: 
  name: lemmy-go-users-service
  namespace: lemmygo
  labels:
    app: lemmy-go-users
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: lemmy-go-users
