apiVersion: v1
kind: Service
metadata: 
  name: lemmy-go-users
  labels:
    app: lemmy-go-users
spec:
  type: LoadBalancer
  ports:
    - name: lemmy-user-service
      port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: lemmy-go-users