apiVersion: v1
kind: Service
metadata: 
  name: lemmy-go-users-service
  labels:
    app: lemmy-go-users
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: lemmy-go-users